version: '3.4'

services:
  db:
    image: postgres:latest
    container_name: nest.postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres/database-generate-scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db:
    driver: local
