services:
  - type: web
    plan: free
    name: transaction-app
    runtime: docker
    repo: https://github.com/SEU_USUARIO/SEU_REPOSITORIO.git
    buildCommand: "yarn install && yarn build"
    startCommand: "yarn start:dev"
    envVars:
      - key: POSTGRES_USER
        value: ${POSTGRES_USER}
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}
      - key: POSTGRES_DB
        value: ${POSTGRES_DB}
      - key: NEW_RELIC_LICENSE_KEY
        value: ${NEW_RELIC_LICENSE_KEY}
      - key: NEW_RELIC_APP_NAME
        value: ${NEW_RELIC_APP_NAME}
      - key: DATABASE_URL
        fromDatabase:
          name: transaction-db
          property: connectionString

  - type: worker
    plan: free
    name: transaction-migration
    runtime: docker
    repo: https://github.com/SEU_USUARIO/SEU_REPOSITORIO.git
    buildCommand: "yarn install && yarn build"
    startCommand: "yarn migration:run"
    envVars:
      - key: POSTGRES_USER
        value: ${POSTGRES_USER}
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}
      - key: POSTGRES_DB
        value: ${POSTGRES_DB}
      - key: NEW_RELIC_LICENSE_KEY
        value: ${NEW_RELIC_LICENSE_KEY}
      - key: NEW_RELIC_APP_NAME
        value: ${NEW_RELIC_APP_NAME}
      - key: DATABASE_URL
        fromDatabase:
          name: transaction-db
          property: connectionString

databases:
  - name: transaction-db
    plan: free
    properties:
      engine: postgres
